### ISSUE TITLE
What entities are supported?

### ISSUE THREAD

**Issue by mcfrojd** [helto4real/hassio-add-ons#1]
What entities and states are supported?

I have sensors coming from the project [Monitor](https://github.com/andrewjfreyer/monitor) where the states are a number from 0 - 100 (BT signal)
Can a sensor like that be used or does it have to have a "home" / "not_home" state?

Can you even use sensors?
In your example i can only see device_trackers

Can i use a binary sensor?

**Comment by helto4real** [comment]
@mcfrojd now it supports "on/off", "true/false"

**Comment by sauloonze** [comment]
Hi @mcfrojd
On solution is set the variable PREF_DEVICE_TRACKER_REPORT to true in the behavior_preferences file.
Reading the monitor documentation: If true, this value will cause monitor to report a 'home' or 'not_home' message to ... /device_tracker conforming to device_tracker mqtt protocol.
I have to try this add on but I don't run hass. :( Anyway, great job!

**Comment by helto4real** [comment]
Thanks !
