### ISSUE TITLE
Not possibile to upgrade to 1.1.4

### ISSUE THREAD

**Issue by jumping2000** [helto4real/hassio-add-ons#10]
hassio supervistor: 192
host system: Debian GNU/Linux 9 (stretch)

19-12-02 13:28:41 INFO (SyncWorker_9) [hassio.docker.addon] Start build 1e72b768/amd64-addon-better_presence:1.1.4
19-12-02 13:29:09 ERROR (SyncWorker_9) [hassio.docker.addon] Can't build 1e72b768/amd64-addon-better_presence:1.1.4: The command '/bin/ash -o pipefail -c apk update &&     apk add --no-cache git make musl-dev go' returned a non-zero code: 5

**Comment by helto4real** [comment]
Try to completely uninstall it (copy your settings before) and install it again. That has been the way people got it working again.

**Comment by helto4real** [comment]
I am doing a new release but need help testing. Copy the **presence** folder from this link 
https://github.com/helto4real/hassio-add-ons/tree/rel_1_2 to local addons folder
Copy settings from old one before uninstall it and add the local one. It should be version 1.2 if correct.

**Comment by jumping2000** [comment]
> I am doing a new release but need help testing. Copy the **presence** folder from this link
> https://github.com/helto4real/hassio-add-ons/tree/rel_1_2 to local addons folder
> Copy settings from old one before uninstall it and add the local one. It should be version 1.2 if correct.

This version works!  
9-12-06 08:56:43 INFO (MainThread) [hassio.addons] Create Home Assistant add-on data folder /data/addons/data/local_better_presence
19-12-06 08:56:43 INFO (SyncWorker_7) [hassio.docker.interface] Pull image helto4real/hassio-better-presence-amd64 tag 1.2.0.
19-12-06 08:56:47 INFO (MainThread) [hassio.addons] Add-on 'local_better_presence' successfully installed
19-12-06 08:57:22 INFO (SyncWorker_7) [hassio.docker.addon] Start Docker add-on helto4real/hassio-better-presence-amd64 with version 1.2.0
19-12-06 08:57:23 INFO (MainThread) [hassio.api.security] /host/info access from local_better_presence
19-12-06 08:57:24 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-12-06 08:57:24 INFO (MainThread) [hassio.api.proxy] WebSocket access from local_better_presence

**Comment by jumping2000** [comment]
> Try to completely uninstall it (copy your settings before) and install it again. That has been the way people got it working again.

I tried it, but the 1.1.4 version gives the same error and does not install, for me the only working version is 1.2

**Comment by helto4real** [comment]
> > Try to completely uninstall it (copy your settings before) and install it again. That has been the way people got it working again.
> 
> I tried it, but the 1.1.4 version gives the same error and does not install, for me the only working version is 1.2

Thanks, I released the 1.2 version now so it should be all fine. Closing this.
