### ISSUE TITLE
Presence always home

### ISSUE THREAD

**Issue by weakapp** [helto4real/hassio-add-ons#17]
Hi.
I have 3 trackers. WiFi, bt and GPS.
When I leave home, both bt and WiFi change state to not_home, but GPS state is always home.
I thought the logic is if others trackers are not home, GPS will check last report and determine if it's home or not. 
But after 30 minutes, it still stay at home, is it an issue or that's the way it is ?

**Comment by helto4real** [comment]
All trackers need to be away to be "not_home"
