### ISSUE TITLE
Status with first letter in capital

### ISSUE THREAD

**Issue by bruxy70** [helto4real/hassio-add-ons#5]
I have a person that combines two device trackers.
But when the trackers are in status "home", the device_tracker.vasek_presence turns to "Home", with first letter in capital. All other device trackers use lower case. Is there a way to change that?
I am using it in a group, and the group does not recognize the people with "Home" status and turns the group to "not_home".
![image](https://user-images.githubusercontent.com/44951610/53623535-aacf7c80-3bfd-11e9-89a4-73f678f69527.png)

  "persons": [
    {
      "id": "vasek",
      "friendly_name": "Vašek",
      "devices": [
        "device_tracker.vasek",
        "device_tracker.vasek_lan"
      ]
    },

**Comment by helto4real** [comment]
I c, I was thinking about doing that but the thing is @bruxy70 you wont need the group since the presence is using several devices to get a stable state. I might do it configurable to use lower case in another release not to break current users.

**Comment by bruxy70** [comment]
I get it. I use a group to combine several persons (and to turn the heating off if nobody is home).
I did it through a template sensor as a workaround for now, but before using better presence I used simple group and it worked just fine.

**Comment by helto4real** [comment]
Now you can with the latest version change to your own values for state. @bruxy70

**Comment by Laurent-MSC** [comment]
Thanks, I was getting crazy do find why my group.all was not working anymore...
