### ISSUE TITLE
Picture missing on device_tracker.[id]_presence

### ISSUE THREAD

**Issue by marchammer2003** [helto4real/hassio-add-ons#7]
Hi.
I have 2 device.trackers set up for "my person" (nmap and BT)
One of the device trackers (nmap) has a picture attached to it and shows just fin on a badge for just the nmap device tracker.
I recall reading in one of your README files that as long as one of the device.trackers has a picture attached to it (as my nmap has) that picture would also be used for the device_tracker.[id]_presence BUT that is not what I experience.

How do I add a picture to a device_tracker.[id]_presence? 
I have tried to add the following in customize.yaml:
```
device_tracker.marc_presence:
  entity_picture: /local/mham.jpg
```

**Comment by helto4real** [comment]
It should be enough to let one of the device trackers have an image. I personally have the GPS device for picture. I will look into it.
